// Generated by HTTP API composition. Do not edit.
import type { PackageContracts } from "@voyzu/types/contracts";
import type { HttpApiRegistration, HttpApiRegisteredRoute } from "@voyzu/types/http-api";

export const installedHttpApiRegistrations: HttpApiRegistration[] = [

];
export const installedHttpApiRoutes: HttpApiRegisteredRoute[] = installedHttpApiRegistrations.flatMap(({packageName,routing})=>Object.entries(routing.routes).map(([id,route])=>({...route,id,packageName})));
