CREATE TABLE IF NOT EXISTS audit_event (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    code TEXT GENERATED ALWAYS AS ('AUDIT-' || id::TEXT) STORED,
    package_code TEXT NOT NULL CHECK (length(btrim(package_code)) > 0),
    company_id BIGINT,
    actor_type actor_type,
    actor_id TEXT,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    entity_code TEXT,
    mutation_id TEXT,
    details_json JSONB,
    creation_date audit_timestamp
);

CREATE INDEX IF NOT EXISTS audit_event_package_company_date_idx
    ON audit_event (package_code, company_id, creation_date DESC, id DESC);

CREATE INDEX IF NOT EXISTS audit_event_package_entity_idx
    ON audit_event (package_code, entity_type, entity_id);

CREATE INDEX IF NOT EXISTS audit_event_mutation_idx
    ON audit_event (mutation_id);
