// Generated by voyzu compose. Do not edit.
import { operation } from "@voyzu/capability/operations";
import { operations as packageOperations1_0 } from "@voyzu/audit/audit/operations";
import { operations as packageOperations2_0 } from "@voyzu/auth/auth/operations";
import { operations as packageOperations2_1 } from "@voyzu/auth/users/operations";
import { operations as packageOperations4_0 } from "@voyzu/localization/countries/operations";
import { operations as packageOperations4_1 } from "@voyzu/localization/currencies/operations";
import { operations as packageOperations5_0 } from "@voyzu/package-management/package-management/operations";

operation.registerModule("@voyzu/audit", "audit", packageOperations1_0);
operation.registerModule("@voyzu/auth", "auth", packageOperations2_0);
operation.registerModule("@voyzu/auth", "users", packageOperations2_1);
operation.registerModule("@voyzu/localization", "countries", packageOperations4_0);
operation.registerModule("@voyzu/localization", "currencies", packageOperations4_1);
operation.registerModule("@voyzu/package-management", "package-management", packageOperations5_0);
