INSERT INTO country (code, name, currency_code, status, creation_actor_type, updated_actor_type)
VALUES
  ('AD', 'Andorra', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AE', 'United Arab Emirates', 'AED', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AF', 'Afghanistan', 'AFN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AG', 'Antigua and Barbuda', 'XCD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AI', 'Anguilla', 'XCD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AL', 'Albania', 'ALL', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AM', 'Armenia', 'AMD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AO', 'Angola', 'AOA', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AQ', 'Antarctica', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AR', 'Argentina', 'ARS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AS', 'American Samoa', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AT', 'Austria', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AU', 'Australia', 'AUD', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AW', 'Aruba', 'AWG', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AX', 'Aland Islands', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('AZ', 'Azerbaijan', 'AZN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BA', 'Bosnia and Herzegovina', 'BAM', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BB', 'Barbados', 'BBD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BD', 'Bangladesh', 'BDT', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BE', 'Belgium', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BF', 'Burkina Faso', 'XOF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BG', 'Bulgaria', 'BGN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BH', 'Bahrain', 'BHD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BI', 'Burundi', 'BIF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BJ', 'Benin', 'XOF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BL', 'Saint Barthelemy', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BM', 'Bermuda', 'BMD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BN', 'Brunei', 'BND', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BO', 'Bolivia', 'BOB', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BR', 'Brazil', 'BRL', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BS', 'Bahamas', 'BSD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BT', 'Bhutan', 'BTN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BV', 'Bouvet Island', 'NOK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BW', 'Botswana', 'BWP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BY', 'Belarus', 'BYN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('BZ', 'Belize', 'BZD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CA', 'Canada', 'CAD', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CC', 'Cocos (Keeling) Islands', 'AUD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CD', 'Democratic Republic of the Congo', 'CDF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CF', 'Central African Republic', 'XAF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CG', 'Republic of the Congo', 'XAF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CH', 'Switzerland', 'CHF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CI', 'Cote d''Ivoire', 'XOF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CK', 'Cook Islands', 'NZD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CL', 'Chile', 'CLP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CM', 'Cameroon', 'XAF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CN', 'China', 'CNY', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CO', 'Colombia', 'COP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CR', 'Costa Rica', 'CRC', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CU', 'Cuba', 'CUP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CV', 'Cabo Verde', 'CVE', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CW', 'Curacao', 'ANG', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CX', 'Christmas Island', 'AUD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CY', 'Cyprus', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('CZ', 'Czechia', 'CZK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('DE', 'Germany', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('DJ', 'Djibouti', 'DJF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('DK', 'Denmark', 'DKK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('DM', 'Dominica', 'XCD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('DO', 'Dominican Republic', 'DOP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('DZ', 'Algeria', 'DZD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('EC', 'Ecuador', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('EE', 'Estonia', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('EG', 'Egypt', 'EGP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('EH', 'Western Sahara', 'MAD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ER', 'Eritrea', 'ERN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ES', 'Spain', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ET', 'Ethiopia', 'ETB', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('FI', 'Finland', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('FJ', 'Fiji', 'FJD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('FK', 'Falkland Islands', 'FKP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('FM', 'Micronesia', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('FO', 'Faroe Islands', 'DKK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('FR', 'France', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GA', 'Gabon', 'XAF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GB', 'United Kingdom', 'GBP', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GD', 'Grenada', 'XCD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GE', 'Georgia', 'GEL', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GF', 'French Guiana', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GG', 'Guernsey', 'GBP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GH', 'Ghana', 'GHS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GI', 'Gibraltar', 'GIP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GL', 'Greenland', 'DKK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GM', 'Gambia', 'GMD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GN', 'Guinea', 'GNF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GP', 'Guadeloupe', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GQ', 'Equatorial Guinea', 'XAF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GR', 'Greece', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GS', 'South Georgia and the South Sandwich Islands', 'GBP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GT', 'Guatemala', 'GTQ', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GU', 'Guam', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GW', 'Guinea-Bissau', 'XOF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('GY', 'Guyana', 'GYD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('HK', 'Hong Kong SAR', 'HKD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('HM', 'Heard Island and McDonald Islands', 'AUD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('HN', 'Honduras', 'HNL', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('HR', 'Croatia', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('HT', 'Haiti', 'HTG', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('HU', 'Hungary', 'HUF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ID', 'Indonesia', 'IDR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IE', 'Ireland', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IL', 'Israel', 'ILS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IM', 'Isle of Man', 'GBP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IN', 'India', 'INR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IO', 'British Indian Ocean Territory', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IQ', 'Iraq', 'IQD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IR', 'Iran', 'IRR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IS', 'Iceland', 'ISK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('IT', 'Italy', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('JE', 'Jersey', 'GBP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('JM', 'Jamaica', 'JMD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('JO', 'Jordan', 'JOD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('JP', 'Japan', 'JPY', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KE', 'Kenya', 'KES', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KG', 'Kyrgyzstan', 'KGS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KH', 'Cambodia', 'KHR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KI', 'Kiribati', 'AUD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KM', 'Comoros', 'KMF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KN', 'St. Kitts & Nevis', 'XCD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KP', 'North Korea', 'KPW', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KR', 'South Korea', 'KRW', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KW', 'Kuwait', 'KWD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KY', 'Cayman Islands', 'KYD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('KZ', 'Kazakhstan', 'KZT', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LA', 'Laos', 'LAK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LB', 'Lebanon', 'LBP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LC', 'St. Lucia', 'XCD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LI', 'Liechtenstein', 'CHF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LK', 'Sri Lanka', 'LKR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LR', 'Liberia', 'LRD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LS', 'Lesotho', 'ZAR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LT', 'Lithuania', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LU', 'Luxembourg', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LV', 'Latvia', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('LY', 'Libya', 'LYD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MA', 'Morocco', 'MAD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MC', 'Monaco', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MD', 'Moldova', 'MDL', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ME', 'Montenegro', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MF', 'St. Martin', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MG', 'Madagascar', 'MGA', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MH', 'Marshall Islands', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MK', 'North Macedonia', 'MKD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ML', 'Mali', 'XOF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MM', 'Myanmar', 'MMK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MN', 'Mongolia', 'MNT', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MO', 'Macao', 'MOP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MP', 'Northern Mariana Islands', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MQ', 'Martinique', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MR', 'Mauritania', 'MRU', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MS', 'Montserrat', 'XCD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MT', 'Malta', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MU', 'Mauritius', 'MUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MV', 'Maldives', 'MVR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MW', 'Malawi', 'MWK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MX', 'Mexico', 'MXN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MY', 'Malaysia', 'MYR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('MZ', 'Mozambique', 'MZN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NA', 'Namibia', 'NAD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NC', 'New Caledonia', 'XPF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NE', 'Niger', 'XOF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NF', 'Norfolk Island', 'AUD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NG', 'Nigeria', 'NGN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NI', 'Nicaragua', 'NIO', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NL', 'Netherlands', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NO', 'Norway', 'NOK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NP', 'Nepal', 'NPR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NR', 'Nauru', 'AUD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NU', 'Niue', 'NZD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('NZ', 'New Zealand', 'NZD', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('OM', 'Oman', 'OMR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PA', 'Panama', 'PAB', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PE', 'Peru', 'PEN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PF', 'French Polynesia', 'XPF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PG', 'Papua New Guinea', 'PGK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PH', 'Philippines', 'PHP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PK', 'Pakistan', 'PKR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PL', 'Poland', 'PLN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PM', 'St. Pierre & Miquelon', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PN', 'Pitcairn Islands', 'NZD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PR', 'Puerto Rico', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PS', 'Palestine', 'ILS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PT', 'Portugal', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PW', 'Palau', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('PY', 'Paraguay', 'PYG', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('QA', 'Qatar', 'QAR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('RE', 'Reunion', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('RO', 'Romania', 'RON', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('RS', 'Serbia', 'RSD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('RU', 'Russia', 'RUB', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('RW', 'Rwanda', 'RWF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SA', 'Saudi Arabia', 'SAR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SB', 'Solomon Islands', 'SBD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SC', 'Seychelles', 'SCR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SD', 'Sudan', 'SDG', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SE', 'Sweden', 'SEK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SG', 'Singapore', 'SGD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'SHP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SI', 'Slovenia', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SJ', 'Svalbard & Jan Mayen', 'NOK', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SK', 'Slovakia', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SL', 'Sierra Leone', 'SLE', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SM', 'San Marino', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SN', 'Senegal', 'XOF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SO', 'Somalia', 'SOS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SR', 'Suriname', 'SRD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SS', 'South Sudan', 'SSP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ST', 'Sao Tome and Principe', 'STN', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SV', 'El Salvador', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SX', 'Sint Maarten', 'ANG', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SY', 'Syria', 'SYP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('SZ', 'Eswatini', 'SZL', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TC', 'Turks & Caicos Islands', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TD', 'Chad', 'XAF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TF', 'French Southern Territories', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TG', 'Togo', 'XOF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TH', 'Thailand', 'THB', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TJ', 'Tajikistan', 'TJS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TK', 'Tokelau', 'NZD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TL', 'Timor-Leste', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TM', 'Turkmenistan', 'TMT', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TN', 'Tunisia', 'TND', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TO', 'Tonga', 'TOP', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TR', 'Turkey', 'TRY', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TT', 'Trinidad & Tobago', 'TTD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TV', 'Tuvalu', 'AUD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TW', 'Taiwan', 'TWD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('TZ', 'Tanzania', 'TZS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('UA', 'Ukraine', 'UAH', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('UG', 'Uganda', 'UGX', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('UM', 'U.S. Outlying Islands', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('US', 'United States', 'USD', 'ACTIVE', 'SYSTEM', 'SYSTEM'),
  ('UY', 'Uruguay', 'UYU', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('UZ', 'Uzbekistan', 'UZS', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('VA', 'Vatican City', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('VC', 'St. Vincent & Grenadines', 'XCD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('VE', 'Venezuela', 'VES', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('VG', 'British Virgin Islands', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('VI', 'U.S. Virgin Islands', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('VN', 'Vietnam', 'VND', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('VU', 'Vanuatu', 'VUV', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('WF', 'Wallis & Futuna', 'XPF', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('WS', 'Samoa', 'WST', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('YE', 'Yemen', 'YER', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('YT', 'Mayotte', 'EUR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ZA', 'South Africa', 'ZAR', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ZM', 'Zambia', 'ZMW', 'INACTIVE', 'SYSTEM', 'SYSTEM'),
  ('ZW', 'Zimbabwe', 'USD', 'INACTIVE', 'SYSTEM', 'SYSTEM')
ON CONFLICT (code) DO UPDATE
SET
    name = EXCLUDED.name,
    currency_code = EXCLUDED.currency_code,
    status = EXCLUDED.status,
    updated_date = NOW(),
    updated_actor_type = 'SYSTEM';
