import Type from "typebox";
import { ArSubledgerEntryResponseDto } from "@voyzu/types/dtos/accounting/modules/ar-subledger-ledger-entries/types/ar-subledger-entry.response.dto";
import { ApSubledgerEntryResponseDto } from "@voyzu/types/dtos/accounting/modules/ap-subledger-ledger-entries/types/ap-subledger-entry.response.dto";
import { ArCounterpartyStatementResponseDto } from "@voyzu/types/dtos/accounting/modules/ar-subledger-statements/types/ar-counterparty-statement.response.dto";
import { ApCounterpartyStatementResponseDto } from "@voyzu/types/dtos/accounting/modules/ap-subledger-statements/types/ap-counterparty-statement.response.dto";
import { ArCounterpartySummaryResponseDto } from "@voyzu/types/dtos/accounting/modules/ar-subledger-counterparties/types/ar-counterparty-summary.response.dto";
import { ApCounterpartySummaryResponseDto } from "@voyzu/types/dtos/accounting/modules/ap-subledger-counterparties/types/ap-counterparty-summary.response.dto";
import { ArInvoiceStatementResponseDto } from "@voyzu/types/dtos/accounting/modules/ar-subledger-invoices/types/ar-invoice-statement.response.dto";
import { ApLedgerEntryDocumentReportResponseDto } from "@voyzu/types/dtos/accounting/modules/ap-subledger-ledger-entries/types/ap-ledger-entry-document-report.response.dto";
import { ArLedgerEntryDocumentReportResponseDto } from "@voyzu/types/dtos/accounting/modules/ar-subledger-ledger-entries/types/ar-ledger-entry-document-report.response.dto";
import { JournalResponseDto } from "@voyzu/types/dtos/accounting/modules/journals/types/journal.response.dto";
export const AccountingScopeDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }) }, { additionalProperties: false });
export const AccountingGetDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), code: Type.String({ minLength: 1 }) }, { additionalProperties: false });
export const arEntryGetResponseDto = Type.Union([ArSubledgerEntryResponseDto, Type.Null()]);
export const arEntryListResponseDto = Type.Array(ArSubledgerEntryResponseDto);
export const apEntryGetResponseDto = Type.Union([ApSubledgerEntryResponseDto, Type.Null()]);
export const apEntryListResponseDto = Type.Array(ApSubledgerEntryResponseDto);
export const arStatementGetResponseDto = Type.Union([ArCounterpartyStatementResponseDto, Type.Null()]);
export const arStatementListResponseDto = Type.Array(ArCounterpartyStatementResponseDto);
export const apStatementGetResponseDto = Type.Union([ApCounterpartyStatementResponseDto, Type.Null()]);
export const apStatementListResponseDto = Type.Array(ApCounterpartyStatementResponseDto);
export const arSummaryGetResponseDto = Type.Union([ArCounterpartySummaryResponseDto, Type.Null()]);
export const arSummaryListResponseDto = Type.Array(ArCounterpartySummaryResponseDto);
export const apSummaryGetResponseDto = Type.Union([ApCounterpartySummaryResponseDto, Type.Null()]);
export const apSummaryListResponseDto = Type.Array(ApCounterpartySummaryResponseDto);
export const arInvoiceGetResponseDto = Type.Union([ArInvoiceStatementResponseDto, Type.Null()]);
export const arInvoiceListResponseDto = Type.Array(ArInvoiceStatementResponseDto);
export const apBillGetResponseDto = Type.Union([ApLedgerEntryDocumentReportResponseDto, Type.Null()]);
export const apBillListResponseDto = Type.Array(ApLedgerEntryDocumentReportResponseDto);
export const arDocumentGetResponseDto = Type.Union([ArLedgerEntryDocumentReportResponseDto, Type.Null()]);
export const arDocumentListResponseDto = Type.Array(ArLedgerEntryDocumentReportResponseDto);
export const journalGetResponseDto = Type.Union([JournalResponseDto, Type.Null()]);
export const journalListResponseDto = Type.Array(JournalResponseDto);

import { TaxSubledgerEntryResponseDto } from "@voyzu/types/dtos/accounting/modules/tax-ledger/types/index";
import { InventoryLedgerEntryDetailResponseDto } from "@voyzu/types/dtos/accounting/modules/inventory-ledger/types/index";
export const TaxEntryGetResponseDto = Type.Union([TaxSubledgerEntryResponseDto, Type.Null()]);
export const InventoryEntryGetResponseDto = Type.Union([InventoryLedgerEntryDetailResponseDto, Type.Null()]);
