import Type from "typebox";
import { ApBillRequestDto as ApBillDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ap-bill.request.dto";
export const ApBillRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ApBillDocumentDto }, { additionalProperties: false });
import { ApBillCancellationRequestDto as ApBillCancellationDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ap-bill-cancellation.request.dto";
export const ApBillCancellationRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ApBillCancellationDocumentDto }, { additionalProperties: false });
import { ApCreditNoteRequestDto as ApCreditNoteDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ap-adjustment.request.dto";
export const ApCreditNoteRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ApCreditNoteDocumentDto }, { additionalProperties: false });
import { ApOpeningBalanceRequestDto as ApOpeningBalanceDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ap-adjustment.request.dto";
export const ApOpeningBalanceRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ApOpeningBalanceDocumentDto }, { additionalProperties: false });
import { ApPaymentRequestDto as ApPaymentDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ap-payment.request.dto";
export const ApPaymentRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ApPaymentDocumentDto }, { additionalProperties: false });
import { ApPaymentApplicationRequestDto as ApPaymentApplicationDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ap-payment-application.request.dto";
export const ApPaymentApplicationRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ApPaymentApplicationDocumentDto }, { additionalProperties: false });
import { ApRefundRequestDto as ApRefundDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ap-adjustment.request.dto";
export const ApRefundRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ApRefundDocumentDto }, { additionalProperties: false });
import { ApWriteOffRequestDto as ApWriteOffDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ap-adjustment.request.dto";
export const ApWriteOffRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ApWriteOffDocumentDto }, { additionalProperties: false });
import { ArCreditNoteRequestDto as ArCreditNoteDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ar-credit-note.request.dto";
export const ArCreditNoteRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ArCreditNoteDocumentDto }, { additionalProperties: false });
import { ArInvoiceRequestDto as ArInvoiceDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ar-invoice.request.dto";
export const ArInvoiceRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ArInvoiceDocumentDto }, { additionalProperties: false });
import { ArInvoiceCancellationRequestDto as ArInvoiceCancellationDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ar-invoice-cancellation.request.dto";
export const ArInvoiceCancellationRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ArInvoiceCancellationDocumentDto }, { additionalProperties: false });
import { ArOpeningBalanceRequestDto as ArOpeningBalanceDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ar-opening-balance.request.dto";
export const ArOpeningBalanceRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ArOpeningBalanceDocumentDto }, { additionalProperties: false });
import { ArReceiptRequestDto as ArReceiptDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ar-receipt.request.dto";
export const ArReceiptRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ArReceiptDocumentDto }, { additionalProperties: false });
import { ArReceiptApplicationRequestDto as ArReceiptApplicationDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ar-receipt-application.request.dto";
export const ArReceiptApplicationRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ArReceiptApplicationDocumentDto }, { additionalProperties: false });
import { ArRefundRequestDto as ArRefundDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ar-refund.request.dto";
export const ArRefundRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ArRefundDocumentDto }, { additionalProperties: false });
import { ArWriteOffRequestDto as ArWriteOffDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ar-write-off.request.dto";
export const ArWriteOffRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: ArWriteOffDocumentDto }, { additionalProperties: false });
import { InventoryAdjustmentRequestDto as InventoryAdjustmentDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/inventory-adjustment.request.dto";
export const InventoryAdjustmentRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: InventoryAdjustmentDocumentDto }, { additionalProperties: false });
import { InventoryIssueRequestDto as InventoryIssueDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/inventory-issue.request.dto";
export const InventoryIssueRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: InventoryIssueDocumentDto }, { additionalProperties: false });
import { InventoryReceiptRequestDto as InventoryReceiptDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/inventory-receipt.request.dto";
export const InventoryReceiptRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: InventoryReceiptDocumentDto }, { additionalProperties: false });
import { LedgerJournalRequestDto as LedgerJournalDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ledger-journal.request.dto";
export const LedgerJournalRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: LedgerJournalDocumentDto }, { additionalProperties: false });
import { LedgerJournalReversalRequestDto as LedgerJournalReversalDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/ledger-journal-reversal.request.dto";
export const LedgerJournalReversalRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: LedgerJournalReversalDocumentDto }, { additionalProperties: false });
import { TaxAdjustmentRequestDto as TaxAdjustmentDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/tax-processing.request.dto";
export const TaxAdjustmentRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: TaxAdjustmentDocumentDto }, { additionalProperties: false });
import { TaxPaymentRequestDto as TaxPaymentDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/tax-processing.request.dto";
export const TaxPaymentRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: TaxPaymentDocumentDto }, { additionalProperties: false });
import { TaxRefundRequestDto as TaxRefundDocumentDto } from "@voyzu/types/dtos/accounting/modules/financial-document-processing-engine/types/tax-processing.request.dto";
export const TaxRefundRequestDto = Type.Object({ organization_id: Type.Integer({ minimum: 1 }), document: TaxRefundDocumentDto }, { additionalProperties: false });
