import "server-only";

import detail from "@voyzu/ui-style/css-modules/detail.module.css";
import typography from "@voyzu/ui-style/css-modules/typography.module.css";
import { Alert } from "@voyzu/ui-components";

import styles from "../../client/system-info.module.css";
import { getSystemInformation, type InfoSection } from "../lib/system-info";

function InformationSection({ title, items }: InfoSection) {
  return (
    <section className={detail.card}>
      <div className={detail.cardHeader}>
        <h2 className={`${typography.sectionHeading} ${detail.cardHeaderTitle}`}>{title}</h2>
      </div>
      <dl className={styles.infoGrid}>
        {items.map((item, index) => (
          <div className={styles.infoRow} key={`${item.label}-${index}`}>
            <dt className={typography.fieldLabel}>{item.label}</dt>
            <dd className={`${typography.bodyText} ${styles.infoValue} ${item.mono ? styles.mono : ""}`}>
              {item.value}
            </dd>
          </div>
        ))}
      </dl>
    </section>
  );
}

export async function SystemInfoPage() {
  const information = await getSystemInformation();
  return (
    <main className={styles.page}>
      <header className={styles.header}>
        <div className={detail.title}>
          <div className={detail.titleIcon}>
            <span className={`material-symbols-outlined ${detail.titleIconSymbol}`}>info</span>
          </div>
          <div>
            <h1 className={typography.pageTitle}>System Information</h1>
            <p className={typography.headingByline}>Generated by the server at {information.generatedAt}</p>
          </div>
        </div>
      </header>
      <Alert
        className={styles.databaseAlert}
        variant="soft"
        color="info"
        title="Database"
        text={information.databaseName}
      />
      <div className={styles.sections}>
        {information.sections.map((section) => <InformationSection key={section.title} {...section} />)}
      </div>
    </main>
  );
}
