CREATE TABLE IF NOT EXISTS installed_packages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
  code TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  top_navigation_visible BOOLEAN NOT NULL DEFAULT TRUE,
  page_routes_visible BOOLEAN NOT NULL DEFAULT TRUE,
  nav_order INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT installed_packages_code_not_blank CHECK (length(btrim(code)) > 0),
  CONSTRAINT installed_packages_nav_order_nonnegative CHECK (nav_order >= 0)
);

ALTER TABLE installed_packages
  ADD COLUMN IF NOT EXISTS top_navigation_visible BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS page_routes_visible BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE installed_packages DROP COLUMN IF EXISTS status;

CREATE INDEX IF NOT EXISTS installed_packages_navigation_idx
  ON installed_packages (nav_order, code);
