CREATE TABLE IF NOT EXISTS installed_packages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
  code TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  status active_status NOT NULL DEFAULT 'ACTIVE',
  nav_order INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT installed_packages_code_not_blank CHECK (length(btrim(code)) > 0),
  CONSTRAINT installed_packages_nav_order_nonnegative CHECK (nav_order >= 0)
);

CREATE INDEX IF NOT EXISTS installed_packages_navigation_idx
  ON installed_packages (nav_order, code);
