import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { PackageContracts } from "@voyzu/types/contracts";
import type { HttpApiRegistration } from "@voyzu/types/http-api";
import { resolveHttpApiContracts } from "@voyzu/http-api/contracts";
import { capabilityHttpApiRegistration } from "@voyzu/http-api/capability-module";
type Descriptor = {
  name: string;
  directory: string;
};
export async function composeHttpApi(runtimeRoot: string, descriptors: Descriptor[]) {
  const directory = join(runtimeRoot, "apps/web/.generated/http-api-routes");
  const definitions = await Promise.all(descriptors.map(async descriptor => {
    const file = join(descriptor.directory, "voyzu.package.ts");
    const {
      default: definition
    } = await import(pathToFileURL(file).href);
    const contracts = definition.contracts as PackageContracts | undefined;
    return {
      ...descriptor,
      file,
      registration: {
        packageName: descriptor.name,
        routing: contracts?.httpApiRouting ?? {
          roots: [],
          routes: {}
        },
        documentation: contracts?.httpApiDocumentation ?? {
          sections: {}
        }
      } satisfies HttpApiRegistration
    };
  }));
  const registrations = [...definitions.map(item => item.registration), capabilityHttpApiRegistration];
  const resolved = resolveHttpApiContracts(registrations);
  for (const descriptor of descriptors) {
    const manifest = JSON.parse(await readFile(join(descriptor.directory, "package.json"), "utf8"));
    for (const [name, target] of Object.entries(manifest.exports ?? {})) {
      if (!/^\.\/[^/]+\/pages\.routes$/.test(name)) continue;
      const relativeFile = typeof target === "string" ? target : (target as {
        import?: string;
      }).import;
      if (!relativeFile) continue;
      const {
        pageRoutes
      } = await import(pathToFileURL(join(descriptor.directory, relativeFile)).href);
      for (const page of Object.values(pageRoutes) as {
        id: string;
        httpApiDocumentationGroupId?: string;
      }[]) {
        if (page.httpApiDocumentationGroupId && !resolved.groups.has(page.httpApiDocumentationGroupId)) {
          throw new Error(`Page ${page.id} references unknown HTTP API documentation group ${page.httpApiDocumentationGroupId}`);
        }
      }
    }
  }
  const groups = {
    "pre-installed": [] as typeof definitions,
    installed: [] as typeof definitions
  };
  for (const definition of definitions) {
    const location = relative(join(runtimeRoot, "packages"), definition.directory);
    groups[location.startsWith("..") ? "installed" : "pre-installed"].push(definition);
  }
  const specifier = (file: string) => {
    const value = relative(directory, file).replaceAll("\\", "/").replace(/\.ts$/, "");
    return value.startsWith(".") ? value : `./${value}`;
  };
  await mkdir(directory, {
    recursive: true
  });
  for (const [name, items] of Object.entries(groups)) {
    const prefix = name === 'pre-installed' ? 'preInstalled' : 'installed';
    const imports = items.map((item, index) => `import package${index} from ${JSON.stringify(specifier(item.file))};`);
    const entries = items.map((item, index) => `  { packageName: ${JSON.stringify(item.name)}, routing: (package${index}.contracts as PackageContracts).httpApiRouting ?? { roots: [], routes: {} }, documentation: (package${index}.contracts as PackageContracts).httpApiDocumentation ?? { sections: {} } }`);
    if (name === 'pre-installed') {
      imports.push('import { capabilityHttpApiRegistration } from "@voyzu/http-api/capability-module";');
      entries.push('  capabilityHttpApiRegistration');
    }
    await writeFile(join(directory, `${name}.ts`), `// Generated by HTTP API composition. Do not edit.
import type { PackageContracts } from "@voyzu/types/contracts";
import type { HttpApiRegistration, HttpApiRegisteredRoute } from "@voyzu/types/http-api";
${imports.join('\n')}
export const ${prefix}HttpApiRegistrations: HttpApiRegistration[] = [
${entries.join(',\n')}
];
export const ${prefix}HttpApiRoutes: HttpApiRegisteredRoute[] = ${prefix}HttpApiRegistrations.flatMap(({packageName,routing})=>Object.entries(routing.routes).map(([id,route])=>({...route,id,packageName})));
`);
  }
  await writeFile(join(directory, "documentation-groups.json"), JSON.stringify(Object.fromEntries([...resolved.groups].map(([id, group]) => [id, group.url])), null, 2) + '\n');
  await writeFile(join(directory, "package-roots.json"), JSON.stringify(Object.fromEntries(registrations.map(({
    packageName,
    routing
  }) => [packageName, routing.roots])), null, 2) + '\n');
  console.log(`Composed HTTP API: ${resolved.routes.size} routes, ${resolved.groups.size} documentation groups.`);
  return registrations;
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const main = async () => {
    const [runtime, input] = process.argv.slice(2);
    if (!runtime || !input) throw new Error("Usage: compose-http-api.ts <runtime> <descriptors-json|@file>");
    const json = input.startsWith('@') ? await readFile(input.slice(1), 'utf8') : input;
    await composeHttpApi(resolve(runtime), JSON.parse(json));
  };
  main().catch(error => {
    console.error(error);
    process.exitCode = 1;
  });
}
