import { mkdir, readFile, writeFile } from "node:fs/promises";
import { isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { resolveInternalApiContracts } from "@voyzu/capability/internal-api";
import type { PackageContracts } from "@voyzu/types/contracts";

type Descriptor = { name: string; directory: string };

export async function composeInternalApi(runtimeRoot: string, _workspaceRoot: string, descriptors: Descriptor[], options: { acceptMissingImplementations?: boolean } = {}) {
  const directory = join(runtimeRoot, "apps/web/.generated/internal-api");
  const specifier = (from: string, to: string) => {
    const value = relative(from, to).replaceAll("\\", "/").replace(/\.ts$/, "");
    return value.startsWith(".") ? value : `./${value}`;
  };
  // Core definitions are always present, even when no installed package implements an extension.
  const coreDescriptors = ["business-objects", "shared-contracts"].map(name => ({
    name: `@voyzu/${name}`, directory: join(runtimeRoot, `packages/@voyzu/${name}`),
  }));
  const candidates = [...coreDescriptors.filter(core => !descriptors.some(pkg => pkg.name === core.name)), ...descriptors];
  const packages = await Promise.all(candidates.map(async descriptor => {
    const file = join(descriptor.directory, "voyzu.package.ts");
    const { default: definition } = await import(pathToFileURL(file).href);
    const location = relative(resolve(runtimeRoot, "packages"), resolve(descriptor.directory));
    const isPlatform = !isAbsolute(location) && location !== ".." && !location.startsWith(`..\\`) && !location.startsWith("../");
    return { ...descriptor, file, isPlatform, contracts: definition.contracts as PackageContracts | undefined };
  }));
  const configuration = resolveInternalApiContracts(packages, options);
  if (options.acceptMissingImplementations) {
    const missing = [...configuration.definitions.keys()].filter(resource => !configuration.providers.has(resource));
    if (missing.length) console.warn(`[voyzu] Accepted missing implementations: ${missing.join(", ")}. Calls remain unavailable.`);
  }
  const groups = {
    "pre-installed": { imports: [] as string[], types: [] as string[], entries: [] as string[] },
    installed: { imports: [] as string[], types: [] as string[], entries: [] as string[] },
  };
  for (const [resource, { definition, packageName }] of configuration.definitions) {
    const owner = packages.find(pkg => pkg.name === packageName)!;
    const provider = configuration.providers.get(resource);
    const providerPackage = provider && packages.find(pkg => pkg.name === provider.packageName)!;
    // Group by the provider's package; unimplemented definitions stay with their owner.
    const { imports, types, entries } = groups[(providerPackage ?? owner).isPlatform ? "pre-installed" : "installed"];
    const alias = `definition${imports.length}`;
    imports.push(`import type ${alias} from ${JSON.stringify(specifier(directory, owner.file))};`);
    types.push(`    ${JSON.stringify(resource)}: typeof ${alias}.contracts.internalApi.defines[${JSON.stringify(resource)}];`);
    const loader = providerPackage
      ? `api => import(${JSON.stringify(specifier(directory, providerPackage.file))}).then(m => (m.default.contracts.internalApi.${provider!.section}[${JSON.stringify(resource)}] as InternalApiImplementationLoader)(api))`
      : "undefined";
    entries.push(`  createLazyInternalApiResource(${JSON.stringify(resource)}, ${JSON.stringify(definition)}, ${loader})`);
  }
  await mkdir(directory, { recursive: true });
  for (const [name, { imports, types, entries }] of Object.entries(groups)) {
    await writeFile(join(directory, `${name}.ts`), `// Generated by voyzu compose. Do not edit.
import { createLazyInternalApiResource } from "@voyzu/capability/internal-api";
import type { InternalApiImplementationLoader, InternalApiResource } from "@voyzu/types/internal-api";
${imports.join("\n")}
declare module "@voyzu/capability/internal-api" {
  interface InternalApiResources {
${types.join("\n")}
  }
}
export const internalApiResources: InternalApiResource[] = [
${entries.join(",\n")}
];
`);
  }
  console.log(`[voyzu] Composed internal API: ${configuration.definitions.size} resources (${groups["pre-installed"].entries.length} pre-installed, ${groups.installed.entries.length} installed).`);
}

// Targeted composition: same descriptor list as the contracts composer; @file is also accepted.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const acceptMissingImplementations = args.includes("--accept-missing-implementations");
  const [runtime, workspace, descriptors, ...extra] = args.filter(arg => arg !== "--accept-missing-implementations");
  const main = async () => {
    if (!runtime || !workspace || !descriptors || extra.length) throw new Error("Usage: compose-internal-api.ts <runtime> <workspace> <descriptors-json|@file> [--accept-missing-implementations]");
    const json = descriptors.startsWith("@") ? await readFile(descriptors.slice(1), "utf8") : descriptors;
    await composeInternalApi(resolve(runtime), resolve(workspace), JSON.parse(json), { acceptMissingImplementations });
  };
  main().catch(error => { console.error(error); process.exitCode = 1; });
}
