import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { createContracts, type ContractPackage } from "@voyzu/capability/contracts";

async function main() {
  const [runtimeArg, workspaceArg, descriptorsJson] = process.argv.slice(2);
  const runtimeRoot = resolve(runtimeArg);
  const workspaceRoot = resolve(workspaceArg);
  const directory = runtimeRoot === workspaceRoot ? join(runtimeRoot, ".generated", "contracts") : join(workspaceRoot, "contracts");
  const descriptors = JSON.parse(descriptorsJson) as Array<{ name: string; directory: string }>;
  const registrations: ContractPackage[] = [];
  const imports: string[] = [];
  const entries: string[] = [];
  const capabilityTypes: string[] = [];
  const masterDataTypes: string[] = [];
  const specifier = (from: string, to: string) => {
    const value = relative(from, to).replaceAll("\\", "/").replace(/\.ts$/, "");
    return value.startsWith(".") ? value : `./${value}`;
  };
  const platformPath = join(runtimeRoot, "contracts", "index.ts");
  const { platformContracts } = await import(pathToFileURL(platformPath).href);
  const candidates = [
    { name: "voyzu-platform", path: platformPath, exportName: "platformContracts", contracts: platformContracts },
    ...await Promise.all(descriptors.map(async (descriptor) => {
      const file = join(descriptor.directory, "voyzu.package.ts");
      const { default: definition } = await import(pathToFileURL(file).href);
      return { name: descriptor.name, path: file, exportName: "default", contracts: definition.contracts };
    })),
  ];
  for (const candidate of candidates) {
    if (!candidate.contracts) continue;
    const index = registrations.length;
    const alias = `package${index}`;
    const expression = candidate.exportName === "default" ? `${alias}.contracts` : alias;
    imports.push(`import ${candidate.exportName === "default" ? alias : `{ platformContracts as ${alias} }`} from ${JSON.stringify(specifier(directory, candidate.path))};`);
    entries.push(`{ name: ${JSON.stringify(candidate.name)}, contracts: ${expression} }`);
    registrations.push({ name: candidate.name, contracts: candidate.contracts });
    for (const name of Object.keys(candidate.contracts.defines?.capabilities ?? {})) capabilityTypes.push(`    ${JSON.stringify(name)}: typeof ${expression}.defines.capabilities[${JSON.stringify(name)}];`);
    for (const name of Object.keys(candidate.contracts.defines?.masterData ?? {})) masterDataTypes.push(`    ${JSON.stringify(name)}: typeof ${expression}.defines.masterData[${JSON.stringify(name)}];`);
  }
  // Fail composition on duplicate providers, undefined contracts, invalid schemas or extension roots.
  // Do not load handlers: composition must not execute business code.
  createContracts(registrations);
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, "index.ts"), `// Generated by voyzu compose. Do not edit.
import { registerContracts } from "@voyzu/capability/contracts";
${imports.join("\n")}
declare module "@voyzu/capability/contracts" {
  interface CapabilityContracts {
${capabilityTypes.join("\n")}
  }
  interface MasterDataContracts {
${masterDataTypes.join("\n")}
  }
}
registerContracts([${entries.join(",\n")}]);
export { capabilities, masterData } from "@voyzu/capability/contracts";
`, "utf8");
  const bridge = join(runtimeRoot, "apps", "web", ".generated", "contracts", "installed.ts");
  await mkdir(dirname(bridge), { recursive: true });
  await writeFile(bridge, `// Generated by voyzu compose. Do not edit.\nexport * from ${JSON.stringify(specifier(dirname(bridge), join(directory, "index.ts")))};\n`, "utf8");
  console.log(`Composed contracts from ${registrations.length} definers/providers.`);
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
