import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { resolveInternalApiContracts, validateInternalApi } from "@voyzu/capability/internal-api";
import type { PackageContracts } from "@voyzu/types/contracts";
import type { InternalApiResource } from "@voyzu/types/internal-api";

type Descriptor = { name: string; directory: string };

export async function composeInternalApi(runtimeRoot: string, workspaceRoot: string, descriptors: Descriptor[]) {
  const directory = runtimeRoot === workspaceRoot
    ? join(runtimeRoot, ".generated", "internal-api")
    : join(workspaceRoot, "internal-api");
  const specifier = (from: string, to: string) => {
    const value = relative(from, to).replaceAll("\\", "/").replace(/\.ts$/, "");
    return value.startsWith(".") ? value : `./${value}`;
  };
  // Core definitions are always present, even when no installed package implements an extension.
  const coreDescriptor = { name: "@voyzu/business-objects", directory: join(runtimeRoot, "packages/@voyzu/business-objects") };
  const candidates = descriptors.some(descriptor => descriptor.name === coreDescriptor.name)
    ? descriptors : [coreDescriptor, ...descriptors];
  const packages = await Promise.all(candidates.map(async descriptor => {
    const file = join(descriptor.directory, "voyzu.package.ts");
    const { default: definition } = await import(pathToFileURL(file).href);
    return { ...descriptor, file, contracts: definition.contracts as PackageContracts | undefined, internalApi: definition.internalApi as readonly InternalApiResource[] | undefined };
  }));
  validateInternalApi(packages);
  const configuration = resolveInternalApiContracts(packages);
  const imports: string[] = [];
  const types: string[] = [];
  const entries: string[] = [];
  for (const [resource, { definition, packageName }] of configuration.definitions) {
    const owner = packages.find(pkg => pkg.name === packageName)!;
    const alias = `definition${imports.length}`;
    imports.push(`import type ${alias} from ${JSON.stringify(specifier(directory, owner.file))};`);
    types.push(`    ${JSON.stringify(resource)}: typeof ${alias}.contracts.defines[${JSON.stringify(resource)}];`);
    const provider = configuration.providers.get(resource);
    const providerPackage = provider && packages.find(pkg => pkg.name === provider.packageName)!;
    const loader = providerPackage
      ? `api => import(${JSON.stringify(specifier(directory, providerPackage.file))}).then(m => (m.default.contracts.implements[${JSON.stringify(resource)}] as InternalApiImplementationLoader)(api))`
      : "undefined";
    entries.push(`  createLazyInternalApiResource(${JSON.stringify(resource)}, ${JSON.stringify(definition)}, ${loader})`);
  }
  for (const [packageIndex, pkg] of packages.entries()) {
    if (!pkg.internalApi?.length) continue;
    const modulePath = JSON.stringify(specifier(directory, pkg.file));
    const alias = `package${packageIndex}`;
    imports.push(`import type ${alias} from ${modulePath};`);
    for (const [index, resource] of pkg.internalApi.entries()) {
      if (configuration.definitions.has(resource.resource)) throw new Error(`Duplicate resource ${resource.resource}`);
      types.push(`    ${JSON.stringify(resource.resource)}: (typeof ${alias}.internalApi)[${index}];`);
      const methods = Object.entries(resource.methods).map(([name, method]) => {
        const key = JSON.stringify(name);
        const metadata = JSON.stringify({ input: method.input, output: method.output, transactional: method.transactional });
        return `${key}: { ...${metadata}, loadHandler: () => import(${modulePath}).then(m => m.default.internalApi[${index}].methods[${key}].loadHandler()) }`;
      });
      entries.push(`  { resource: ${JSON.stringify(resource.resource)}, methods: { ${methods.join(",\n")} } }`);
    }
  }
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, "package.json"), JSON.stringify({ private: true, type: "module" }, null, 2) + "\n");
  await writeFile(join(directory, "index.ts"), `// Generated by voyzu compose. Do not edit.
import { createLazyInternalApiResource, registerInternalApi } from "@voyzu/capability/internal-api";
import type { InternalApiImplementationLoader } from "@voyzu/types/internal-api";
${imports.join("\n")}
declare module "@voyzu/capability/internal-api" {
  interface InternalApiResources {
${types.join("\n")}
  }
}
registerInternalApi([
${entries.join(",\n")}
]);
export { internalApi } from "@voyzu/capability/internal-api";
`);
  const bridge = join(runtimeRoot, "apps/web/.generated/internal-api/installed.ts");
  await mkdir(dirname(bridge), { recursive: true });
  await writeFile(bridge, `// Generated by voyzu compose. Do not edit.\nexport * from ${JSON.stringify(specifier(dirname(bridge), join(directory, "index.ts")))};\n`);
  console.log(`[voyzu] Composed internal API: ${entries.length} resources.`);
}

// Targeted composition: same descriptor list as the contracts composer; @file is also accepted.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [runtime, workspace, descriptors] = process.argv.slice(2);
  const main = async () => {
    if (!runtime || !workspace || !descriptors) throw new Error("Usage: compose-internal-api.ts <runtime> <workspace> <descriptors-json|@file>");
    const json = descriptors.startsWith("@") ? await readFile(descriptors.slice(1), "utf8") : descriptors;
    await composeInternalApi(resolve(runtime), resolve(workspace), JSON.parse(json));
  };
  main().catch(error => { console.error(error); process.exitCode = 1; });
}
