import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { validateCrossPackageApi } from "@voyzu/capability/cross-package-api";
import type { CrossPackageApiResource } from "@voyzu/types/cross-package-api";

type Descriptor = { name: string; directory: string };

export async function composeCrossPackageApi(runtimeRoot: string, workspaceRoot: string, descriptors: Descriptor[]) {
  const directory = runtimeRoot === workspaceRoot
    ? join(runtimeRoot, ".generated", "cross-package-api")
    : join(workspaceRoot, "cross-package-api");
  const specifier = (from: string, to: string) => {
    const value = relative(from, to).replaceAll("\\", "/").replace(/\.ts$/, "");
    return value.startsWith(".") ? value : `./${value}`;
  };
  const packages = await Promise.all(descriptors.map(async descriptor => {
    const file = join(descriptor.directory, "voyzu.package.ts");
    const { default: definition } = await import(pathToFileURL(file).href);
    return { ...descriptor, file, crossPackageApi: definition.crossPackageApi as readonly CrossPackageApiResource[] | undefined };
  }));
  validateCrossPackageApi(packages);
  const imports: string[] = [];
  const types: string[] = [];
  const entries: string[] = [];
  for (const [packageIndex, pkg] of packages.entries()) {
    if (!pkg.crossPackageApi?.length) continue;
    const modulePath = JSON.stringify(specifier(directory, pkg.file));
    const alias = `package${packageIndex}`;
    imports.push(`import type ${alias} from ${modulePath};`);
    for (const [index, resource] of pkg.crossPackageApi.entries()) {
      types.push(`    ${JSON.stringify(resource.resource)}: (typeof ${alias}.crossPackageApi)[${index}];`);
      const methods = Object.entries(resource.methods).map(([name, method]) => {
        const key = JSON.stringify(name);
        const metadata = JSON.stringify({ input: method.input, output: method.output, transactional: method.transactional });
        return `${key}: { ...${metadata}, loadHandler: () => import(${modulePath}).then(m => m.default.crossPackageApi[${index}].methods[${key}].loadHandler()) }`;
      });
      entries.push(`  { resource: ${JSON.stringify(resource.resource)}, methods: { ${methods.join(",\n")} } }`);
    }
  }
  await mkdir(directory, { recursive: true });
  await writeFile(join(directory, "package.json"), JSON.stringify({ private: true, type: "module" }, null, 2) + "\n");
  await writeFile(join(directory, "index.ts"), `// Generated by voyzu compose. Do not edit.
import { registerCrossPackageApi } from "@voyzu/capability/cross-package-api";
${imports.join("\n")}
declare module "@voyzu/capability/cross-package-api" {
  interface CrossPackageApiResources {
${types.join("\n")}
  }
}
registerCrossPackageApi([
${entries.join(",\n")}
]);
export { crossPackageApi } from "@voyzu/capability/cross-package-api";
`);
  const bridge = join(runtimeRoot, "apps/web/.generated/cross-package-api/installed.ts");
  await mkdir(dirname(bridge), { recursive: true });
  await writeFile(bridge, `// Generated by voyzu compose. Do not edit.\nexport * from ${JSON.stringify(specifier(dirname(bridge), join(directory, "index.ts")))};\n`);
  console.log(`[voyzu] Composed cross-package API: ${entries.length} resources.`);
}

// Targeted composition: same descriptor list as the contracts composer; @file is also accepted.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [runtime, workspace, descriptors] = process.argv.slice(2);
  const main = async () => {
    if (!runtime || !workspace || !descriptors) throw new Error("Usage: compose-cross-package-api.ts <runtime> <workspace> <descriptors-json|@file>");
    const json = descriptors.startsWith("@") ? await readFile(descriptors.slice(1), "utf8") : descriptors;
    await composeCrossPackageApi(resolve(runtime), resolve(workspace), JSON.parse(json));
  };
  main().catch(error => { console.error(error); process.exitCode = 1; });
}
