// Generated by voyzu compose. Do not edit.
import { events as platformEvents } from "@voyzu/capability/events";


type EventCompositionState = {
  cleanups: (() => void)[];
};

const eventGlobal = globalThis as typeof globalThis & {
  __voyzuEventComposition?: EventCompositionState;
};

eventGlobal.__voyzuEventComposition?.cleanups.forEach((cleanup) => cleanup());
const cleanups: (() => void)[] = [];

eventGlobal.__voyzuEventComposition = { cleanups };
