CREATE TABLE IF NOT EXISTS party (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    code business_code NOT NULL UNIQUE,
    name display_name NOT NULL
);

-- Extend the existing Party records; preserve IDs used by counterparties.
ALTER TABLE party
    ADD COLUMN IF NOT EXISTS status active_status,
    ADD COLUMN IF NOT EXISTS creation_date audit_timestamp,
    ADD COLUMN IF NOT EXISTS creation_actor_type actor_type,
    ADD COLUMN IF NOT EXISTS creation_user_id TEXT,
    ADD COLUMN IF NOT EXISTS creation_mutation_id UUID,
    ADD COLUMN IF NOT EXISTS updated_date audit_timestamp,
    ADD COLUMN IF NOT EXISTS updated_actor_type actor_type,
    ADD COLUMN IF NOT EXISTS updated_user_id TEXT,
    ADD COLUMN IF NOT EXISTS updated_mutation_id UUID,
    ADD COLUMN IF NOT EXISTS deletion_date audit_timestamp,
    ADD COLUMN IF NOT EXISTS deletion_actor_type actor_type,
    ADD COLUMN IF NOT EXISTS deletion_user_id TEXT,
    ADD COLUMN IF NOT EXISTS deletion_mutation_id UUID;

DROP TRIGGER IF EXISTS party_audit_trigger ON party;
CREATE TRIGGER party_audit_trigger BEFORE INSERT OR UPDATE OR DELETE ON party
FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn('@voyzu/party');
