// Generated by voyzu compose. Do not edit.
"use client";
import type { ComponentType, ReactNode } from "react";
import { ClientComponentProvider } from "@voyzu/ui-surface/client";
const registrations: readonly { id: string; loadComponent: () => Promise<ComponentType<any>> }[] = [];
export function ComposedClientComponents({ children }: { children: ReactNode }) {
  return <ClientComponentProvider registrations={registrations}>{children}</ClientComponentProvider>;
}
