// Generated by voyzu compose. Do not edit.
"use client";
import type { ComponentType, ReactNode } from "react";
import { ClientComponentProvider } from "@voyzu/ui-surface/client";
import { clientComponents as clientComponents0 } from "@voyzu/audit/common/client-components";
const registrations: readonly { id: string; loadComponent: () => Promise<ComponentType<any>> }[] = [...Object.values(clientComponents0)];
export function ComposedClientComponents({ children }: { children: ReactNode }) {
  return <ClientComponentProvider registrations={registrations}>{children}</ClientComponentProvider>;
}
