DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type
    WHERE typname = 'user_role'
      AND typnamespace = current_schema()::regnamespace
  ) THEN
    CREATE TYPE user_role AS ENUM (
      'ADMIN',
      'STANDARD'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type
    WHERE typname = 'user_access_mode'
      AND typnamespace = current_schema()::regnamespace
  ) THEN
    CREATE TYPE user_access_mode AS ENUM (
      'UI',
      'API',
      'UI_AND_API'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    code business_code UNIQUE CHECK (length(code) <= 20),
    email TEXT UNIQUE,
    display_name display_name NOT NULL,
    password_hash TEXT NOT NULL,
    role user_role NOT NULL,
    access_mode user_access_mode NOT NULL DEFAULT 'UI',
    implementer_access BOOLEAN NOT NULL DEFAULT false,
    status active_status,

    creation_date audit_timestamp,
    creation_actor_type actor_type,
    creation_user_id TEXT,
    creation_mutation_id UUID,

    updated_date audit_timestamp,
    updated_actor_type actor_type,
    updated_user_id TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT app_user_email_trim CHECK (email IS NULL OR email = btrim(email)),
    CONSTRAINT app_user_email_not_blank CHECK (email IS NULL OR length(email) > 0),
    CONSTRAINT app_user_implementer_access_admin_only CHECK (implementer_access = false OR role = 'ADMIN')
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'app_user'
      AND column_name = 'show_developer_links'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name = 'app_user'
      AND column_name = 'implementer_access'
  ) THEN
    ALTER TABLE app_user RENAME COLUMN show_developer_links TO implementer_access;
  END IF;
END $$;

ALTER TABLE app_user DROP CONSTRAINT IF EXISTS app_user_implementer_access_admin_only;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_enum enum_value
    JOIN pg_type enum_type ON enum_type.oid = enum_value.enumtypid
    WHERE enum_type.typname = 'user_role'
      AND enum_value.enumlabel IN ('ORGANIZATION_USER', 'COMPANY_USER')
  ) THEN
    CREATE TYPE user_role_replacement AS ENUM ('ADMIN', 'STANDARD');
    ALTER TABLE app_user
      ALTER COLUMN role TYPE user_role_replacement
      USING role::text::user_role_replacement;
    DROP TYPE user_role;
    ALTER TYPE user_role_replacement RENAME TO user_role;
  END IF;
END $$;

ALTER TABLE app_user DROP CONSTRAINT IF EXISTS app_user_developer_links_admin_only;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'app_user_implementer_access_admin_only'
      AND conrelid = 'app_user'::regclass
  ) THEN
    ALTER TABLE app_user
      ADD CONSTRAINT app_user_implementer_access_admin_only
      CHECK (implementer_access = false OR role = 'ADMIN');
  END IF;
END $$;
