DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type
    WHERE typname = 'user_role'
      AND typnamespace = current_schema()::regnamespace
  ) THEN
    CREATE TYPE user_role AS ENUM (
      'ADMIN',
      'ORGANIZATION_USER',
      'COMPANY_USER'
    );
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type
    WHERE typname = 'user_access_mode'
      AND typnamespace = current_schema()::regnamespace
  ) THEN
    CREATE TYPE user_access_mode AS ENUM (
      'UI',
      'API',
      'UI_AND_API'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000),
    code business_code UNIQUE CHECK (length(code) <= 20),
    email TEXT UNIQUE,
    display_name display_name NOT NULL,
    password_hash TEXT NOT NULL,
    role user_role NOT NULL,
    access_mode user_access_mode NOT NULL DEFAULT 'UI',
    show_developer_links BOOLEAN NOT NULL DEFAULT false,
    status active_status,

    creation_date audit_timestamp,
    creation_actor_type actor_type,
    creation_user_id TEXT,
    creation_mutation_id UUID,

    updated_date audit_timestamp,
    updated_actor_type actor_type,
    updated_user_id TEXT,
    updated_mutation_id UUID,

    deletion_date audit_timestamp,
    deletion_actor_type actor_type,
    deletion_user_id TEXT,
    deletion_mutation_id UUID,

    CONSTRAINT app_user_email_trim CHECK (email IS NULL OR email = btrim(email)),
    CONSTRAINT app_user_email_not_blank CHECK (email IS NULL OR length(email) > 0),
    CONSTRAINT app_user_developer_links_admin_only CHECK (show_developer_links = false OR role = 'ADMIN')
);
