// Generated by voyzu compose. Do not edit.
import { command } from "@voyzu/capability/commands";
import { commands as packageCommands1_0 } from "@voyzu/audit/audit/commands";
import { commands as packageCommands2_0 } from "@voyzu/auth/auth/commands";
import { commands as packageCommands2_1 } from "@voyzu/auth/users/commands";
import { commands as packageCommands4_0 } from "@voyzu/localization/countries/commands";
import { commands as packageCommands4_1 } from "@voyzu/localization/currencies/commands";
import { commands as packageCommands5_0 } from "@voyzu/package-management/package-management/commands";

command.registerModule("@voyzu/audit", "audit", packageCommands1_0);
command.registerModule("@voyzu/auth", "auth", packageCommands2_0);
command.registerModule("@voyzu/auth", "users", packageCommands2_1);
command.registerModule("@voyzu/localization", "countries", packageCommands4_0);
command.registerModule("@voyzu/localization", "currencies", packageCommands4_1);
command.registerModule("@voyzu/package-management", "package-management", packageCommands5_0);
