// Generated by voyzu compose. Do not edit.
import { createLazyInternalApiResource } from "@voyzu/capability/internal-api";
import type { InternalApiImplementationLoader, InternalApiResource } from "@voyzu/types/internal-api";

declare module "@voyzu/capability/internal-api" {
  interface InternalApiResources {

  }
}
export const internalApiResources: InternalApiResource[] = [

];
